<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $img = function ($seed) {
          return  "https://dummyjson.com/image/600x600?text={$seed}";
        };
        $products = [
            [
                'id' => 'p1',
                'slug' => 'pisang-cavendish',
                'name' => 'Pisang Cavendish',
                'unit' => '1 sisir (±800 g)',
                'price' => 28900,
                'original_price' => 34900,
                'category_slug' => 'buah-segar',
                'images' => [$img('pisang-cavendish')],
                'rating' => 4.8,
                'stock' => 24,
                'is_popular' => true,
                'description' => 'Pisang cavendish matang pohon, manis dan pulen. Cocok untuk sarapan atau smoothie.',
            ],
            [
                'id' => 'p2',
                'slug' => 'apel-fuji',
                'name' => 'Apel Fuji',
                'unit' => '4 pcs (±600 g)',
                'price' => 42000,
                'original_price' => null,
                'category_slug' => 'buah-segar',
                'images' => [$img('apel-fuji')],
                'rating' => 4.6,
                'stock' => 18,
                'is_popular' => false,
                'description' => 'Apel fuji renyah dengan rasa manis segar. Sudah dicuci dan siap santap.',
            ],
            [
                'id' => 'p3',
                'slug' => 'jeruk-nipis-organik',
                'name' => 'Jeruk Nipis Organik Astro Farm',
                'unit' => '200 g',
                'price' => 35500,
                'original_price' => 39900,
                'category_slug' => 'buah-segar',
                'images' => [$img('jeruk-nipis-organik')],
                'rating' => 4.5,
                'stock' => 30,
                'is_popular' => false,
                'description' => 'Jeruk nipis organik segar, cocok untuk masakan dan minuman.',
            ],
            [
                'id' => 'p4',
                'slug' => 'bayam-hijau',
                'name' => 'Bayam Hijau',
                'unit' => '1 ikat (±250 g)',
                'price' => 5900,
                'original_price' => null,
                'category_slug' => 'sayur-segar',
                'images' => [$img('bayam-hijau')],
                'rating' => 4.4,
                'stock' => 40,
                'is_popular' => true,
                'description' => 'Bayam hijau segar dipanen pagi hari. Enak untuk sayur bening.',
            ],
            [
                'id' => 'p5',
                'slug' => 'wortel-berastagi',
                'name' => 'Wortel Berastagi',
                'unit' => '500 g',
                'price' => 12500,
                'original_price' => 15000,
                'category_slug' => 'sayur-segar',
                'images' => [$img('wortel-berastagi')],
                'rating' => 4.5,
                'stock' => 35,
                'is_popular' => false,
                'description' => 'Wortel manis dari Berastagi. Sudah dibersihkan dari tanah.',
            ],
            [
                'id' => 'p6',
                'slug' => 'tomat-merah',
                'name' => 'Tomat Merah',
                'unit' => '500 g',
                'price' => 11900,
                'original_price' => null,
                'category_slug' => 'sayur-segar',
                'images' => [$img('tomat-merah')],
                'rating' => 4.3,
                'stock' => 28,
                'is_popular' => false,
                'description' => 'Tomat merah segar, padat dan tidak lembek. Serbaguna untuk masakan apa pun.',
            ],
            [
                'id' => 'p7',
                'slug' => 'dada-ayam-fillet',
                'name' => 'Dada Ayam Fillet',
                'unit' => '500 g',
                'price' => 38900,
                'original_price' => 45000,
                'category_slug' => 'daging-ayam-seafood',
                'images' => [$img('dada-ayam-fillet')],
                'rating' => 4.7,
                'stock' => 20,
                'is_popular' => true,
                'description' => 'Fillet dada ayam tanpa tulang dan kulit. Higienis, langsung siap dimasak.',
            ],
            [
                'id' => 'p8',
                'slug' => 'daging-sapi-giling',
                'name' => 'Daging Sapi Giling',
                'unit' => '250 g',
                'price' => 42500,
                'original_price' => null,
                'category_slug' => 'daging-ayam-seafood',
                'images' => [$img('daging-sapi-giling')],
                'rating' => 4.6,
                'stock' => 15,
                'is_popular' => false,
                'description' => 'Daging sapi giling segar untuk bakso, burger, atau bolognese.',
            ],
            [
                'id' => 'p9',
                'slug' => 'udang-vaname',
                'name' => 'Udang Vaname Kupas',
                'unit' => '250 g',
                'price' => 49900,
                'original_price' => 55000,
                'category_slug' => 'daging-ayam-seafood',
                'images' => [$img('udang-vaname')],
                'rating' => 4.5,
                'stock' => 12,
                'is_popular' => false,
                'description' => 'Udang vaname sudah dikupas dan dibuang kotorannya. Tinggal masak.',
            ],
            [
                'id' => 'p10',
                'slug' => 'telur-ayam-negeri',
                'name' => 'Telur Ayam Negeri',
                'unit' => '10 pcs (±600 g)',
                'price' => 27500,
                'original_price' => 31000,
                'category_slug' => 'telur-tahu-tempe',
                'images' => [$img('telur-ayam-negeri')],
                'rating' => 4.8,
                'stock' => 50,
                'is_popular' => true,
                'description' => 'Telur ayam negeri segar, dikemas rapi agar tidak pecah saat pengiriman.',
            ],
            [
                'id' => 'p11',
                'slug' => 'tempe-batang',
                'name' => 'Tempe Batang',
                'unit' => '1 papan (±400 g)',
                'price' => 8500,
                'original_price' => null,
                'category_slug' => 'telur-tahu-tempe',
                'images' => [$img('tempe-batang')],
                'rating' => 4.6,
                'stock' => 45,
                'is_popular' => false,
                'description' => 'Tempe kedelai padat dan wangi. Produksi harian dari mitra lokal.',
            ],
            [
                'id' => 'p12',
                'slug' => 'tahu-putih',
                'name' => 'Tahu Putih',
                'unit' => '10 pcs',
                'price' => 9900,
                'original_price' => null,
                'category_slug' => 'telur-tahu-tempe',
                'images' => [$img('tahu-putih')],
                'rating' => 4.4,
                'stock' => 38,
                'is_popular' => false,
                'description' => 'Tahu putih lembut, cocok digoreng atau dijadikan sup.',
            ],
            [
                'id' => 'p13',
                'slug' => 'susu-uht-full-cream',
                'name' => 'Susu UHT Full Cream',
                'unit' => '1 liter',
                'price' => 21900,
                'original_price' => 24500,
                'category_slug' => 'susu-olahan',
                'images' => [$img('susu-uht')],
                'rating' => 4.7,
                'stock' => 42,
                'is_popular' => true,
                'description' => 'Susu UHT full cream tanpa pengawet. Simpan di kulkas setelah dibuka.',
            ],
            [
                'id' => 'p14',
                'slug' => 'keju-cheddar-slice',
                'name' => 'Keju Cheddar Slice',
                'unit' => '10 lembar (170 g)',
                'price' => 29500,
                'original_price' => null,
                'category_slug' => 'susu-olahan',
                'images' => [$img('keju-cheddar')],
                'rating' => 4.5,
                'stock' => 25,
                'is_popular' => false,
                'description' => 'Keju lembaran praktis untuk roti bakar dan sandwich.',
            ],
            [
                'id' => 'p15',
                'slug' => 'yogurt-plain',
                'name' => 'Yogurt Plain',
                'unit' => '200 ml',
                'price'=> 15900,
                'original_price' => 18000,
                'category_slug' => 'susu-olahan',
                'images' => [$img('yogurt-plain')],
                'rating' => 4.3,
                'stock' => 0,
                'is_popular' => false,
                'description' => 'Yogurt plain tanpa gula tambahan. Enak dicampur buah atau granola.',
            ],
            [
                'id' => 'p16',
                'slug' => 'beras-premium-5kg',
                'name' => 'Beras Premium',
                'unit' => '5 kg',
                'price' => 74900,
                'original_price' => 82000,
                'category_slug' => 'kebutuhan-pokok',
                'images' => [$img('beras-premium')],
                'rating' => 4.8,
                'stock' => 20,
                'is_popular' => true,
                'description' => 'Beras premium pulen, bulir utuh dan bersih. Cukup untuk kebutuhan sebulan.',
            ],
            [
                'id' => 'p17',
                'slug' => 'minyak-goreng-2l',
                'name' => 'Minyak Goreng',
                'unit' => '2 liter',
                'price' => 38500,
                'original_price' => null,
                'category_slug' => 'kebutuhan-pokok',
                'images' => [$img('minyak-goreng')],
                'rating' => 4.6,
                'stock' => 30,
                'is_popular' => true,
                'description' => 'Minyak goreng kemasan pouch, jernih dan tidak mudah tengik.',
            ],
            [
                'id' => 'p18',
                'slug' => 'gula-pasir-1kg',
                'name' => 'Gula Pasir',
                'unit' => '1 kg',
                'price' => 17900,
                'original_price' => 19500,
                'category_slug' => 'kebutuhan-pokok',
                'images' => [$img('gula-pasir')],
                'rating' => 4.5,
                'stock' => 36,
                'is_popular' => false,
                'description' => 'Gula pasir putih dengan butiran halus, mudah larut.',
            ],
            [
                'id' => 'p19',
                'slug' => 'bawang-merah',
                'name' => 'Bawang Merah',
                'unit' => '250 g',
                'price' => 13900,
                'original_price' => null,
                'category_slug' => 'bahan-masak-bumbu',
                'images' => [$img('bawang-merah')],
                'rating' => 4.4,
                'stock' => 40,
                'is_popular' => false,
                'description' => 'Bawang merah kering pilihan, aroma tajam dan tidak busuk.',
            ],
            [
                'id' => 'p20',
                'slug' => 'bawang-putih',
                'name' => 'Bawang Putih',
                'unit' => '250 g',
                'price' => 12500,
                'original_price' => 14000,
                'category_slug' => 'bahan-masak-bumbu',
                'images' => [$img('bawang-putih')],
                'rating' => 4.4,
                'stock' => 40,
                'is_popular' => false,
                'description' => 'Bawang putih siung besar, mudah dikupas.',
            ],
            [
                'id' => 'p21',
                'slug' => 'kecap-manis',
                'name' => 'Kecap Manis',
                'unit' => '520 ml',
                'price' => 24900,
                'original_price' => null,
                'category_slug' => 'bahan-masak-bumbu',
                'images' => [$img('kecap-manis')],
                'rating' => 4.7,
                'stock' => 28,
                'is_popular' => false,
                'description' => 'Kecap manis kental dari kedelai hitam pilihan.',
            ],
            [
                'id' => 'p22',
                'slug' => 'cabai-merah-keriting',
                'name' => 'Cabai Merah Keriting',
                'unit' => '250 g',
                'price' => 18900,
                'original_price' => 22000,
                'category_slug' => 'bahan-masak-bumbu',
                'images' => [$img('cabai-merah')],
                'rating' => 4.2,
                'stock' => 22,
                'is_popular' => false,
                'description' => 'Cabai merah keriting segar, pedasnya pas untuk sambal.',
            ],
            [
                'id' => 'p23',
                'slug' => 'nugget-ayam',
                'name' => 'Nugget Ayam',
                'unit' => '500 g',
                'price' => 45900,
                'original_price' => 52000,
                'category_slug' => 'makanan-beku',
                'images' => [$img('nugget-ayam')],
                'rating' => 4.7,
                'stock' => 26,
                'is_popular' => true,
                'description' => 'Nugget ayam renyah di luar, lembut di dalam. Stok andalan anak kos.',
            ],
            [
                'id' => 'p24',
                'slug' => 'sosis-sapi',
                'name' => 'Sosis Sapi',
                'unit' => '360 g',
                'price' => 33500,
                'original_price' => null,
                'category_slug' => 'makanan-beku',
                'images' => [$img('sosis-sapi')],
                'rating' => 4.5,
                'stock' => 24,
                'is_popular' => false,
                'description' => 'Sosis sapi siap goreng atau bakar. Simpan di freezer.',
            ],
            [
                 'id' => 'p25',
                 'slug' => 'kentang-goreng-beku',
                 'name' => 'Kentang Goreng Beku',
                 'unit' => '1 kg',
                 'price' => 39900,
                 'original_price' => 44000,
                 'category_slug' => 'makanan-beku',
                 'images' => [$img('kentang-goreng')],
                 'rating' => 4.6,
                 'stock' => 18,
                 'is_popular' => false,
                 'description' => 'Kentang goreng potong shoestring, hasil gorengan renyah dan seragam.',
            ],
            [
                'id' => 'p26',
                'slug' => 'keripik-kentang-balado',
                'name' => 'Keripik Kentang Balado',
                'unit' => '150 g',
                'price' => 14500,
                'original_price' => null,
                'category_slug' => 'snack',
                'images' => [$img('keripik-kentang')],
                'rating' => 4.5,
                'stock' => 40,
                'is_popular' => false,
                'description' => 'Keripik kentang renyah dengan bumbu balado pedas manis.',
            ],
            [
                'id' => 'p27',
                'slug' => 'biskuit-cokelat',
                'name' => 'Biskuit Cokelat',
                'unit' => '120 g',
                'price' => 9900,
                'original_price' => 11500,
                'category_slug' => 'snack',
                'images' => [$img('biskuit-cokelat')],
                'rating' => 4.4,
                'stock' => 55,
                'is_popular' => false,
                'description' => 'Biskuit renyah dengan lapisan krim cokelat.',
            ],
            [
                'id' => 'p28',
                'slug' => 'cokelat-batang-almond',
                'name' => 'Cokelat Batang Almond',
                'unit' => '65 g',
                'price' => 18500,
                'original_price' => null,
                'category_slug' => 'snack',
                'images' => [$img('cokelat-almond')],
                'rating' => 4.8,
                'stock' => 32,
                'is_popular' => false,
                'description' => 'Cokelat susu dengan potongan almond panggang.',
            ],
            [
                'id' => 'p29',
                'slug' => 'air-mineral-1500ml',
                'name' => 'Air Mineral',
                'unit' => '1500 ml',
                'price' => 6500,
                'original_price' => null,
                'category_slug' => 'minuman',
                'images' => [$img('air-mineral')],
                'rating' => 4.9,
                'stock' => 80,
                'is_popular' => true,
                'description' => 'Air mineral dalam kemasan botol besar. Stok wajib di rumah.',
            ],
            [
                'id' => 'p30',
                'slug' => 'kopi-susu-botol',
                'name' => 'Kopi Susu Botol',
                'unit' => '250 ml',
                'price' => 16900,
                'original_price' => 19900,
                'category_slug' => 'minuman',
                'images' => [$img('kopi-susu')],
                'rating' => 4.7,
                'stock' => 34,
                'is_popular' => true,
                'description' => 'Kopi susu dingin siap minum dengan gula aren.',
            ],
            [
                'id' => 'p31',
                'slug' => 'teh-kotak',
                'name' => 'Teh Kotak',
                'unit' => '300 ml',
                'price' => 6900,
                'original_price' => null,
                'category_slug' => 'minuman',
                'images' => [$img('teh-kotak')],
                'rating' => 4.3,
                'stock' => 48,
                'is_popular' => false,
                'description' => 'Teh melati manis dalam kemasan kotak, praktis dibawa.',
            ],
            [
                'id' => 'p32',
                'slug' => 'sabun-mandi-cair',
                'name' => 'Sabun Mandi Cair',
                'unit' => '450 ml',
                'price' => 32900,
                'original_price' => 38000,
                'category_slug' => 'perawatan-diri',
                'images' => [$img('sabun-cair')],
                'rating' => 4.6,
                'stock' => 30,
                'is_popular' => false,
                'description' => 'Sabun mandi cair dengan busa lembut dan wangi tahan lama.',
            ],
            [
                'id' => 'p33',
                'slug' => 'shampoo-anti-ketombe',
                'name' => 'Shampoo Anti Ketombe',
                'unit' => '340 ml',
                'price' => 45900,
                'original_price' => null,
                'category_slug' => 'perawatan-diri',
                'images' => [$img('shampoo-ketombe')],
                'rating' => 4.5,
                'stock' => 22,
                'is_popular' => false,
                'description' => 'Shampoo untuk membantu mengurangi ketombe dan gatal di kulit kepala.',
            ],
            [
                'id' => 'p34',
                'slug' => 'pasta-gigi',
                'name' => 'Pasta Gigi',
                'unit' => '190 g',
                'price' => 19900,
                'original_price' => 22500,
                'category_slug' => 'perawatan-diri',
                'images' => [$img('pasta-gigi')],
                'rating' => 4.7,
                'stock' => 44,
                'is_popular' => false,
                'description' => 'Pasta gigi dengan fluoride untuk perlindungan gigi berlubang.',
            ],
            [
                'id' => 'p35',
                'slug' => 'deterjen-cair',
                'name' => 'Deterjen Cair',
                'unit' => '800 ml',
                'price' => 28900,
                'original_price' => 33000,
                'category_slug' => 'perawatan-rumah',
                'images' => [$img('deterjen-cair')],
                'rating' => 4.6,
                'stock' => 26,
                'is_popular' => true,
                'description' => 'Deterjen cair konsentrat, ampuh angkat noda tanpa merusak serat kain.',
            ],
            [
                'id' => 'p36',
                'slug' => 'sabun-cuci-piring',
                'name' => 'Sabun Cuci Piring',
                'unit' => '780 ml',
                'price' => 21500,
                'original_price' => null,
                'category_slug' => 'perawatan-rumah',
                'images' => [$img('sabun-piring')],
                'rating' => 4.5,
                'stock' => 33,
                'is_popular' => false,
                'description' => 'Sabun cuci piring pekat, cepat mengangkat lemak membandel.',
            ],
            [
                'id' => 'p37',
                'slug' => 'pembersih-lantai',
                'name' => 'Pembersih Lantai',
                'unit' => '800 ml',
                'price' => 24900,
                'original_price' => 27500,
                'category_slug' => 'perawatan-rumah',
                'images' => [$img('pembersih-lantai')],
                'rating' => 4.4,
                'stock' => 21,
                'is_popular' => false,
                'description' => 'Pembersih lantai dengan wangi segar tahan lama.',
            ],
        ];
        foreach ($products as $product) {
            Product::updateOrCreate(['id' => $product['id']], $product);
        }
    }
}
